steps:

  - label: "Echo meta evm_loader_branch"
    commands:
      - "echo NEON_EVM_REVISION: ${EVM_LOADER_REVISION:-latest}"
      - "echo NEON_EVM_BRANCH: ${EVM_LOADER_BRANCH:-develop}"
      - "echo NEON_EVM_REPO: ${NEON_EVM_REPO}"
      - "echo SOLANA_REVISION: ${SOLANA_REVISION}"
      - "echo EVM_LOADER_FULL_TEST_SUITE: ${EVM_LOADER_FULL_TEST_SUITE}"
    agents:
      queue: "testing"

  - label: "Check if the full test suite is to be run"
    key: "to-substitute-label"
    if: |
        (build.pull_request.base_branch == "develop" && !build.pull_request.draft) ||
        (build.source == "trigger_job" && build.env("EVM_LOADER_FULL_TEST_SUITE") == "true")
    commands:
      - echo "EVM_LOADER_FULL_TEST_SUITE:" ${EVM_LOADER_FULL_TEST_SUITE}
      - echo "BUILDKITE_PULL_REQUEST:" ${BUILDKITE_PULL_REQUEST}

