steps:

  - label: "Example Test 1"
    command: echo "draft?:" build.pull_request.draft
    if: !build.pull_request.draft
    priority: 1

  - block: "Release"
    prompt: "Fill out the details for release"
    fields:
      - text: "Release Name"
        key: "release-name"

  - label: "Example Test 2"
    command: sleep 5 && echo check parallel execution 2
    priority: 3
