steps:

  - label: "Echo meta evm_loader_branch"
    commands:
      - echo EVM_LOADER_FULL_TEST_SUITE - ${EVM_LOADER_FULL_TEST_SUITE}
      - echo EVM_LOADER_REVISION - ${EVM_LOADER_REVISION}
      - echo EVM_LOADER_BRANCH - ${EVM_LOADER_BRANCH}
      - echo SOLANA_REVISION - ${SOLANA_REVISION}
    agents:
      queue: "testing"

  - label: "Check if the full test suite is to be run"
    key: "to-substitute-label"
    if: |
        (build.pull_request.base_branch == "develop" && !build.pull_request.draft)
        || (build.source == "trigger_job" && build.env("EVM_LOADER_FULL_TEST_SUITE") == "true")
    commands:
      - echo RUN FULL TEST SUITE
      - echo "EVM_LOADER_FULL_TEST_SUITE:\ ${EVM_LOADER_FULL_TEST_SUITE}"

