steps:

  - label: "Echo meta evm_loader_branch"
    commands:
      - echo EVM_LOADER_REVISION - ${EVM_LOADER_REVISION:-latest}
      - echo EVM_LOADER_BRANCH - ${EVM_LOADER_BRANCH:-develop}
      - echo SOLANA_REVISION - ${SOLANA_REVISION}
    agents:
      queue: "testing"

  - label: "Check if the full test suite is to be run"
    key: "to-substitute-label"
    if: |
        (build.pull_request.base_branch == "develop" && !build.pull_request.draft)
    commands:
      - echo "EVM_LOADER_FULL_TEST_SUITE:" ${EVM_LOADER_FULL_TEST_SUITE}

