steps:

  - label: "Example Test 1"
    command: echo Buildkite source - $BUILDKITE_SOURCE '- NEON_EVM_BRANCH:' $(build.env("EVM_LOADER_BRANCH"))
    if: !build.pull_request.draft
    priority: 1

  - label: "Example Test 2"
    command: sleep 5 && echo check parallel execution 2
    priority: 3
    skip: "My reason"