steps:

  - label: "Example Test 1"
    command: sleep 5 && echo check parallel execution 1
    priority: 1

  - label: "Example Test 2"
    command: sleep 5 && echo check parallel execution 2
    priority: 3
    skip: "My reason"