steps:
#  - label: "define if for full test suite"
#    command: buildkite-agent meta-data set "full_test_suite" "true"
#    agents:
#      queue: "testing"

  - label: "Example Test 1"
    command: echo evm_loader_branch - $(buildkite-agent meta-data get "evm_loader_branch" --default "false")
    agents:
      queue: "testing"

  - label: "Example Test 2"
    command: echo "full_test_suite:" ${FULL_TEST_SUITE}
    agents:
      queue: "testing"