steps:
#  - label: "define if for full test suite"
#    command: buildkite-agent meta-data set "full_test_suite" "true"
#    agents:
#      queue: "testing"

  - label: "Echo meta evm_loader_branch"
    commands:
      - echo evm_loader_branch - $(buildkite-agent meta-data get "full_test_suite" --job ${NEON_EVM_JOB_ID}  --default "false")
      - echo BUILDKITE_JOB_ID - ${BUILDKITE_JOB_ID}
      - echo BUILDKITE_TRIGGERED_FROM_BUILD_ID - ${BUILDKITE_TRIGGERED_FROM_BUILD_ID}
      - echo NEON_EVM_JOB_ID - ${NEON_EVM_JOB_ID}
      - export GGBB="ajf;lkj asdk;jf;lkdjsaf"
      - echo GGBB - ${GGBB}
    agents:
      queue: "testing"

  - label: "Echo env FULL_TEST_SUITE"
    commands:
      - echo "full_test_suite:" ${FULL_TEST_SUITE} -
      - echo BUILDKITE_JOB_ID - ${BUILDKITE_JOB_ID}
    agents:
      queue: "testing"