steps:

  - label: "Example Test 1"
    command: echo "full_test_suite:" $(buildkite-agent meta-data get "full_test_suite" --default "false")
    agents:
      queue: "testing"

  - label: "Example Test 2"
    command: sleep 5 && echo check parallel execution 2
    priority: 3
    skip: "My reason"
    agents:
      queue: "testing"